app.py
from flask import Flask
from routes import pages
import os
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def create_app():
    app = Flask(__name__)
    client = MongoClient(os.environ.get('MONGO_URI'))
    app.db = client.get_default_database()

    app.register_blueprint(pages)

    return app

routes.py
from dateutil.utils import today
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from collections import defaultdict
import datetime
import uuid

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")


@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        return [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]

    return {"date_range": date_range}


def today_at_midnight():
    today = datetime.datetime.today()
    return today - datetime.timedelta(hours=today.hour, minutes=today.minute, seconds=today.second)


@pages.route("/")
def index():
    print([e for e in current_app.db.habits.find({})])  # Changed pages.db to current_app.db
    date_str = request.args.get("date")
    selected_date = datetime.datetime.fromisoformat(date_str) if date_str else datetime.datetime.today()

    habits_on_date = current_app.db.habits.find({"added": {"$lte": selected_date}})
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template("index.html", title="HTracker - Home", habits=habits_on_date, completions=completions,
                           selected_date=selected_date)


@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()
    if request.method == "POST":
        try:
            current_app.db.habits.insert_one(
                {
                    "_id": uuid.uuid4().hex,
                    "added": today,
                    "name": request.form.get("habit")
                }
            )
            return redirect(url_for("habits.index"))  # Ensure to redirect after adding a habit
        except Exception as e:
            print(f"Error adding habit: {e}")  # Add error logging here

    return render_template("add_habit.html", title="HTracker - Add habit", selected_date=today)


@pages.route("/complete", methods=["POST"])
def complete_habit():
    date_str = request.form.get("date")
    habit = request.form.get("habitId")
    date = datetime.datetime.fromisoformat(date_str)
    current_app.db.completions.insert_one({"habit": habit, "date": date})
    return redirect(url_for("habits.index", date=date_str))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
   <form class="form" method="post">
      <textarea class="form_input" id="habit" name="habit" rows="3" placeholder="Add a new daily habit"></textarea>
      <button class="form_button" type="submit">Add</button>
   </form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
        {% for habit in habits %}
        {% set completed = habit["_id"] in completions %}
        {% if completed %}
        <div class="habit completed">
            <p class="habit_name">{{ habit["name"] }}</p>
            <svg class="habit_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
        </div>
        {% else %}
        <div class="habit">
            <form method="post" class="habit_form" action="{{ url_for('habits.complete_habit') }}">
                <input type="hidden" name="habitId" value="{{ habit['_id'] }}">
                <input type="hidden" name="date" value="{{ selected_date }}">
                <button type="submit" class="habit_button">{{ habit["name"] }}</button>
            </form>
        </div>
        {% endif %}
        {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link href="http://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

    {% block head_content %} {% endblock %}
</head>
<body>
<header class="header">
    <h1 class="header_logo">
        <a href="{{ url_for('habits.index') }}" class="header_link">Habits</a>
    </h1>
    {% if "add" not in request.endpoint %}
    <a href="{{ url_for('habits.add_habit') }}" class="header_link">+ Add new</a>
    {% endif %}
</header>

<main class="main">
    <section class="dates">
    {% for date in date_range(selected_date) %}
    <a class="dates_link {{ 'dates_link-current' if loop.index0 == 3 else '' }}"
       href="{{ url_for('habits.index', date=date) }}"
    >
        <time class="date" datetime="{{ date }}">
            <span>{{ date.strftime("%a") }}</span>  {# Назва дня тижня #}
            <span>{{ date.strftime("%d") }}</span>  {# День місяця #}
        </time>
    </a>
    {% endfor %}
    </section>
    {% block main_content %} {% endblock %}
</main>

</body>
</html>